<?php
/* English — interface language */

return [
    /* Site */
    'site.title'        => 'Central Clinical Hospital No. 2',
    'site.subtitle'     => 'Main Medical Administration under the Administration of the President of the Republic of Uzbekistan',
    'site.full_name'    => 'Central Clinical Hospital No. 2 of the Main Medical Administration under the Administration of the President of the Republic of Uzbekistan',
    'site.short'        => 'CCH No. 2',

    /* Common */
    'common.loading'    => 'Loading…',
    'common.error'      => 'An error occurred. Please try again.',
    'common.retry'      => 'Retry',
    'common.optional'   => 'optional',
    'common.back'       => 'Back',
    'common.skip'       => 'Skip to content',
    'common.more'       => 'More',

    /* Navigation */
    'nav.home'          => 'Home',
    'nav.departments'   => 'Departments',
    'nav.doctors'       => 'Doctors',
    'nav.news'          => 'News',
    'nav.contacts'      => 'Contacts',
    'nav.anticorruption'=> 'Anti-corruption',
    'nav.book'          => 'Book appointment',
    'nav.menu'          => 'Menu',

    'topbar.working'    => 'Mon–Fri 08:00–18:00',
    'topbar.emergency'  => 'Emergency',
    'topbar.registry'   => 'Registration desk',

    /* Hero */
    'hero.badge'        => 'Main Medical Administration under the Administration of the President of Uzbekistan',
    'hero.title'        => 'Central Clinical Hospital No. 2',
    'hero.lead'         => 'A state hospital in Tashkent. More than 60 physicians see patients; diagnostics run on 3T MRI, 128-slice CT and our own angiograph. Online booking is available 24/7.',
    'hero.f1'           => '3 Tesla MRI and 128-slice CT',
    'hero.f2'           => 'Highest-category doctors, Candidates and Doctors of Sciences',
    'hero.f3'           => 'Online appointment booking — around the clock',
    'hero.f4'           => 'In-house laboratory: same-day results',
    'hero.cta_book'     => 'Book an appointment',
    'hero.cta_about'    => 'About the hospital',

    /* Quick doctor search */
    'search.title'      => 'Quick doctor search',
    'search.department' => 'Specialty',
    'search.any'        => 'Any specialty',
    'search.name_ph'    => 'For example: Karimova',
    'search.submit'     => 'Find a doctor',

    /* Statistics */
    'stats.years_v'     => '45+',
    'stats.years'       => 'years in practice',
    'stats.doctors_v'   => '60+',
    'stats.doctors'     => 'physicians on staff',
    'stats.depts_v'     => '10',
    'stats.depts'       => 'clinical departments',
    'stats.patients_v'  => '120,000+',
    'stats.patients'    => 'visits per year',

    /* Departments */
    'depts.title'       => 'Departments',
    'depts.lead'        => 'Consultations, diagnostics and treatment across 10 departments. Online booking is open for each of them.',
    'depts.book'        => 'Book',

    /* About */
    'about.title'       => 'About the hospital',
    'about.lead'        => 'A state hospital of the Main Medical Administration under the Administration of the President of Uzbekistan.',
    'about.p1'          => 'Central Clinical Hospital No. 2 admits adult patients in Mirzo Ulugbek district of Tashkent. The institution has operated for over 45 years and employs more than 60 physicians of the highest and first categories, Candidates and Doctors of Medical Sciences.',
    'about.p2'          => 'It brings together specialized departments, a diagnostics centre and its own clinical diagnostic laboratory, which issues test results on the day of the visit.',
    'about.tech_title'  => 'Diagnostic equipment',
    'about.t1'          => '3 Tesla MRI',
    'about.t2'          => '128-slice CT',
    'about.t3'          => 'Expert ultrasound',
    'about.t4'          => 'Angiography system',
    'about.t5'          => 'Digital radiography',
    'about.t6'          => 'Express diagnostics laboratory',
    'about.badge1'      => 'Licence of the Ministry of Health of the Republic of Uzbekistan',
    'about.badge2'      => 'Clinical base of research programmes',

    /* Doctors */
    'docs.title'        => 'Doctors',
    'docs.lead'         => 'Physicians with academic degrees and professional categories. Experience is listed on each card.',
    'docs.all'          => 'All doctors',
    'docs.office'       => 'Office {n}',
    'docs.experience'   => 'Experience {n}',
    'docs.book'         => 'Book',
    'docs.empty'        => 'No doctors found.',
    'docs.filter_all'   => 'All departments',
    'docs.page_title'   => 'Medical staff',
    'docs.page_lead'    => 'Choose a specialist and book an appointment at a convenient time.',
    'docs.found'        => 'Doctors found: {n}',

    /* News */
    'news.title'        => 'News and announcements',
    'news.lead'         => 'Official hospital news and information for patients.',
    'news.all'          => 'All news',
    'news.more'         => 'More',
    'news.empty'        => 'No news yet.',
    'news.page_title'   => 'News and official announcements',
    'news.page_lead'    => 'Events, announcements and information for patients.',
    'news.back'         => 'Back to all news',

    /* Call to action */
    'cta.title'         => 'Book an appointment online',
    'cta.text'          => 'Choose the specialty, doctor and a convenient time — the confirmation appears immediately. It takes no more than two minutes.',
    'cta.button'        => 'Go to online booking',

    /* Footer */
    'footer.about'      => 'A treatment and prevention institution of the Main Medical Administration under the Administration of the President of Uzbekistan.',
    'footer.nav'        => 'Navigation',
    'footer.depts'      => 'Departments',
    'footer.patients'   => 'For patients',
    'footer.contacts'   => 'Contacts',
    'footer.docs'       => 'Regulatory documents',
    'footer.anticorruption' => 'Anti-corruption policy',
    'footer.emergency'  => 'Emergency: 103',
    'footer.rights'     => 'All rights reserved.',

    /* Contacts */
    'contacts.page_title'    => 'Contacts and legal information',
    'contacts.page_lead'     => 'How to contact the hospital and find us.',
    'contacts.registry'      => 'Registration desk',
    'contacts.emergency'     => 'Emergency service',
    'contacts.email'         => 'E-mail',
    'contacts.address'       => 'Address',
    'contacts.hours'         => 'Working hours',
    'contacts.requisites'    => 'Official information',
    'contacts.req_full_name' => 'Full legal name',
    'contacts.map_title'     => 'How to find us',
    'contacts.map_text'      => 'By public transport to the "Clinical Hospital" stop (buses 12, 45, 71). Free parking for patients is available at the main entrance.',
    'contacts.map_open'      => 'Open on the map',

    /* Anti-corruption */
    'ac.page_title'        => 'Anti-corruption policy',
    'ac.page_lead'         => 'The hospital adheres to the principle of zero tolerance for corruption.',
    'ac.intro'             => 'Central Clinical Hospital No. 2 ensures transparency of medical services and does not tolerate any form of corrupt practice. All services are provided strictly within the established procedure and the legislation of the Republic of Uzbekistan.',
    'ac.principles_title'  => 'Core principles',
    'ac.p1'                => 'Transparency of the procedure and conditions of medical care.',
    'ac.p2'                => 'Inadmissibility of demanding or providing rewards to employees.',
    'ac.p3'                => 'Objectivity and impartiality in the provision of services.',
    'ac.p4'                => 'Safety and confidentiality of reports about corruption facts.',
    'ac.laws_title'        => 'Regulatory documents',
    'ac.l1'                => 'Law of the Republic of Uzbekistan "On Combating Corruption" (LRU-419 of 10.01.2017).',
    'ac.l2'                => 'Decree of the President of the Republic of Uzbekistan No. PD-5729 of 21.06.2019 "On measures to further improve the anti-corruption system of the Republic of Uzbekistan".',
    'ac.l3'                => 'Legislation of the Republic of Uzbekistan on personal data and civil service.',
    'ac.hotline_title'     => 'Hotline',
    'ac.hotline_text'      => 'Facts of extortion, unlawful payments or other corrupt practices can be reported anonymously via the hotline phone and the administration e-mail. Every report is reviewed within the established time limits.',

    /* 404 page */
    'p404.title' => 'Page not found',
    'p404.text'  => 'The requested page does not exist or has been moved.',
    'p404.home'  => 'Go home',

    /* Online booking */
    'bk.title'        => 'Online appointment booking',
    'bk.lead'         => 'Five steps: specialty, doctor, date, patient details and confirmation. It takes about two minutes.',
    'bk.s1'           => 'Specialty',
    'bk.s2'           => 'Doctor',
    'bk.s3'           => 'Date and time',
    'bk.s4'           => 'Your details',
    'bk.s5'           => 'Confirmation',
    'bk.step'         => 'Step {n} of 5',
    'bk.search_ph'    => 'Search specialty…',
    'bk.no_doctors'   => 'There are currently no doctors available for booking in this department.',
    'bk.doctors_found'=> '{n}',
    'bk.choose_date'  => 'Choose the date and time of your visit',
    'bk.slots_title'  => 'Available time',
    'bk.no_slots'     => 'There are no free slots on the selected date. Please choose another day.',
    'bk.select_slot'  => 'Choose a convenient time',
    'bk.name'         => 'Patient full name',
    'bk.name_ph'      => 'Karimov Alisher Botirovich',
    'bk.phone'        => 'Phone number',
    'bk.birth'        => 'Date of birth',
    'bk.passport'     => 'Passport (series and number)',
    'bk.passport_ph'  => 'AA1234567',
    'bk.pinfl'        => 'PINFL',
    'bk.pinfl_ph'     => '14 digits',
    'bk.comment'      => 'Comment / complaint',
    'bk.comment_ph'   => 'Briefly describe your complaints or the purpose of the visit',
    'bk.consent'      => 'I consent to the processing of my personal data for the purpose of appointment booking.',
    'bk.submit'       => 'Book appointment',
    'bk.submitting'   => 'Submitting…',
    'bk.back'         => 'Back',
    'bk.next'         => 'Next',
    'bk.errors'       => 'Please check that the form is filled in correctly',
    'bk.err_name'     => 'Enter the full name (at least 3 characters, letters only).',
    'bk.err_phone'    => 'Enter a valid number in +998 (XX) XXX-XX-XX format.',
    'bk.err_birth'    => 'Check the date of birth.',
    'bk.err_passport' => 'Passport format: two letters and 7 digits (AA1234567).',
    'bk.err_pinfl'    => 'PINFL must contain 14 digits.',
    'bk.err_comment'  => 'The comment must not exceed 1000 characters.',
    'bk.err_consent'  => 'Consent to personal data processing is required.',
    'bk.err_generic'  => 'Could not create the booking. Please check the selected data.',
    'bk.err_rate'     => 'Too many requests from your address. Please try again in a few minutes.',
    'bk.err_slot'     => 'This time has just been taken. Please choose another one.',
    'bk.err_day'      => 'No appointments are held on this day. Please choose another date.',
    'bk.err_csrf'     => 'The session has expired. Refresh the page and try again.',
    'bk.err_honeypot' => 'The request was rejected by the protection system.',
    'bk.done_title'   => 'You are booked',
    'bk.done_lead'    => 'Save the request number — give it at the registration desk when you visit.',
    'bk.ticket'       => 'Request number',
    'bk.instr_title'  => 'Visit instructions',
    'bk.i1'           => 'Arrive at the hospital 15–20 minutes before your appointment.',
    'bk.i2'           => 'Bring your passport or ID card.',
    'bk.i3'           => 'If available — a referral, insurance policy and results of previous examinations.',
    'bk.i4'           => 'Go to the registration desk (1st floor, lobby) to confirm your arrival.',
    'bk.i5'           => 'If you cannot come — notify the registration desk by the phone number below.',
    'bk.again'        => 'Book another patient',
    'bk.home'         => 'Go home',
    'bk.print'        => 'Print request',
    'bk.summary'      => 'Your appointment',
    'bk.f_doctor'     => 'Doctor',
    'bk.f_dept'       => 'Department',
    'bk.f_date'       => 'Date',
    'bk.f_time'       => 'Time',
    'bk.f_office'     => 'Office',
    'bk.f_patient'    => 'Patient',
    'bk.f_phone'      => 'Phone',
    'bk.change'       => 'Change',
    'bk.today'        => 'Today',
    'bk.required_note'=> '* — required fields',

    /* Months */
    'month.1'  => 'January',
    'month.2'  => 'February',
    'month.3'  => 'March',
    'month.4'  => 'April',
    'month.5'  => 'May',
    'month.6'  => 'June',
    'month.7'  => 'July',
    'month.8'  => 'August',
    'month.9'  => 'September',
    'month.10' => 'October',
    'month.11' => 'November',
    'month.12' => 'December',
];
