<?php
/* O'zbekcha (lotin) — interfeys tili */

return [
    /* Sayt */
    'site.title'        => '2-sonli markaziy klinik shifoxona',
    'site.subtitle'     => "O'zbekiston Respublikasi Prezidenti Administratsiyasi huzuridagi Bosh tibbiyot boshqarmasi",
    'site.full_name'    => "O'zbekiston Respublikasi Prezidenti Administratsiyasi huzuridagi Bosh tibbiyot boshqarmasining 2-sonli markaziy klinik shifoxonasi",
    'site.short'        => 'MKSh № 2',

    /* Umumiy */
    'common.loading'    => 'Yuklanmoqda…',
    'common.error'      => "Xatolik yuz berdi. Qayta urinib ko'ring.",
    'common.retry'      => 'Qayta urinish',
    'common.optional'   => 'ixtiyoriy',
    'common.back'       => 'Orqaga',
    'common.skip'       => "Matnga o'tish",
    'common.more'       => "Batafsil",

    /* Navigatsiya */
    'nav.home'          => 'Bosh sahifa',
    'nav.departments'   => "Bo'limlar",
    'nav.doctors'       => 'Shifokorlar',
    'nav.news'          => 'Yangiliklar',
    'nav.contacts'      => 'Aloqa',
    'nav.anticorruption'=> "Korrupsiyaga qarshi kurash",
    'nav.book'          => "Qabulga yozilish",
    'nav.menu'          => 'Menyu',

    'topbar.working'    => 'Du–Pay 08:00–18:00',
    'topbar.emergency'  => 'Tez yordam',
    'topbar.registry'   => "Ro'yxatga olish bo'limi",

    /* Bosh ekran */
    'hero.badge'        => "O'zbekiston Respublikasi Prezidenti Administratsiyasi huzuridagi Bosh tibbiyot boshqarmasi",
    'hero.title'        => '2-sonli markaziy klinik shifoxona',
    'hero.lead'         => 'Davlat shifoxonasi — Toshkentda. Qabulni 60 dan ortiq shifokor olib boradi, diagnostika MRT, KT va angiografda bajariladi. Online yozish sutka davomida ishlaydi.',
    'hero.f1'           => '3 Tesla MRT va 128 qatlamli KT',
    'hero.f2'           => "Oliy toifali shifokorlar, fan nomzodlari va doktorlari",
    'hero.f3'           => "Qabulga onlayn yozilish — 24 soat",
    'hero.f4'           => "O'z laboratoriyasi: natijalar murojaat kunining o'zida",
    'hero.cta_book'     => "Qabulga yozilish",
    'hero.cta_about'    => 'Shifoxona haqida',

    /* Shifokorni tez izlash */
    'search.title'      => "Shifokorni tez izlash",
    'search.department' => "Yo'nalish",
    'search.any'        => "Har qanday yo'nalish",
    'search.name_ph'    => 'Masalan: Karimova',
    'search.submit'     => 'Shifokorni topish',

    /* Statistika */
    'stats.years_v'     => '45+',
    'stats.years'       => 'yillik faoliyat',
    'stats.doctors_v'   => '60+',
    'stats.doctors'     => 'shtatdagi shifokor',
    'stats.depts_v'     => '10',
    'stats.depts'       => "klinik bo'lim",
    'stats.patients_v'  => '120 000+',
    'stats.patients'    => 'murojaat, yiliga',

    /* Bo'limlar */
    'depts.title'       => "Bo'limlar",
    'depts.lead'        => "10 bo'limda qabul, diagnostika va davolash. Har bir bo'limga online yozish ochiq.",
    'depts.book'        => 'Yozilish',

    /* Shifoxona haqida */
    'about.title'       => 'Shifoxona haqida',
    'about.lead'        => 'Prezident Administratsiyasi huzuridagi Bosh tibbiyot boshqarmasining davlat shifoxonasi.',
    'about.p1'          => "2-sonli markaziy klinik shifoxona Toshkentning Mirzo Ulug'bek tumanida kattalarni qabul qiladi. Muassasa 45 yildan ortiq faoliyat yuritadi; shtatda oliy va birinchi toifadagi, tibbiyot fanlari nomzodi va doktori unvoniga ega 60 dan ortiq shifokor ishlaydi.",
    'about.p2'          => "Tarkibda ixtisoslashtirilgan bo'limlar, diagnostika markazi va o'z klinik-diagnostik laboratoriyasi. Laboratoriya tahlil natijalarini murojaat kuni beradi.",
    'about.tech_title'  => 'Diagnostika uskunasi',
    'about.t1'          => '3 Tesla MRT',
    'about.t2'          => '128 qatlamli KT',
    'about.t3'          => "Ekspert UZI",
    'about.t4'          => 'Angiografik tizim',
    'about.t5'          => 'Raqamli rentgenografiya',
    'about.t6'          => 'Tezkor diagnostika laboratoriyasi',
    'about.badge1'      => "O'zbekiston Respublikasi Sog'liqni saqlash vazirligi litsenziyasi",
    'about.badge2'      => 'Ilmiy-tadqiqot dasturlarining klinik bazasi',

    /* Shifokorlar */
    'docs.title'        => 'Shifokorlar',
    'docs.lead'         => "Ilmiy unvon va toifaga ega mutaxassislar. Har bir kartochkada tajriba ko'rsatilgan.",
    'docs.all'          => 'Barcha shifokorlar',
    'docs.office'       => '{n}-xona',
    'docs.experience'   => 'Staj {n}',
    'docs.book'         => 'Yozilish',
    'docs.empty'        => 'Shifokorlar topilmadi.',
    'docs.filter_all'   => "Barcha bo'limlar",
    'docs.page_title'   => 'Shifokorlar tarkibi',
    'docs.page_lead'    => "Mutaxassisni tanlang va qulay vaqtda qabulga yoziling.",
    'docs.found'        => 'Topilgan shifokorlar: {n}',

    /* Yangiliklar */
    'news.title'        => 'Yangiliklar va e\'lonlar',
    'news.lead'         => "Shifoxonaning rasmiy yangiliklari va bemorlar uchun ma'lumotlar.",
    'news.all'          => 'Barcha yangiliklar',
    'news.more'         => "Batafsil",
    'news.empty'        => "Hozircha yangiliklar yo'q.",
    'news.page_title'   => 'Yangiliklar va rasmiy e\'lonlar',
    'news.page_lead'    => "Tadbirlar, e'lonlar va bemorlar uchun ma'lumotlar.",
    'news.back'         => "Barcha yangiliklarga",

    /* Harakatga chaqiruv */
    'cta.title'         => "Qabulga onlayn yoziling",
    'cta.text'          => "Yo'nalishni, shifokorni va qulay vaqtni tanlang — tasdiqlash darhol ko'rsatiladi. Bu ikki daqiqadan ko'p vaqt olmaydi.",
    'cta.button'        => "Onlayn yozilishga o'tish",

    /* Futer */
    'footer.about'      => 'Prezident Administratsiyasi huzuridagi Bosh tibbiyot boshqarmasining davolash-profilaktika muassasasi.',
    'footer.nav'        => 'Navigatsiya',
    'footer.depts'      => "Bo'limlar",
    'footer.patients'   => 'Bemorlarga',
    'footer.contacts'   => 'Aloqa',
    'footer.docs'       => "Normativ hujjatlar",
    'footer.anticorruption' => "Korrupsiyaga qarshi siyosat",
    'footer.emergency'  => 'Tez yordam: 103',
    'footer.rights'     => 'Barcha huquqlar himoyalangan.',

    /* Aloqa */
    'contacts.page_title'    => 'Aloqa va rekvizitlar',
    'contacts.page_lead'     => "Shifoxona bilan qanday bog'lanish va qanday yetib borish mumkin.",
    'contacts.registry'      => "Ro'yxatga olish bo'limi",
    'contacts.emergency'     => 'Tez yordam xizmati',
    'contacts.email'         => 'Elektron pochta',
    'contacts.address'       => 'Manzil',
    'contacts.hours'         => 'Ish tartibi',
    'contacts.requisites'    => 'Rasmiy rekvizitlar',
    'contacts.req_full_name' => "To'liq nomlanishi",
    'contacts.map_title'     => 'Qanday yetib borish',
    'contacts.map_text'      => "Jamoaat transporti bilan «Klinik shifoxona» to'xtoviga qadar (12, 45, 71-avtobuslar). Bemorlar uchun asosiy kirish tomonida bepul avtoturargoh ishlaydi.",
    'contacts.map_open'      => 'Xaritada ochish',

    /* Korrupsiyaga qarshi kurash */
    'ac.page_title'        => "Korrupsiyaga qarshi siyosat",
    'ac.page_lead'         => "Shifoxona korrupsiyaga nisbatan nolatorlik printsipiga rioya qiladi.",
    'ac.intro'             => "2-sonli markaziy klinik shifoxona tibbiy xizmatlar ko'rsatishda shaffoflikni ta'minlaydi va korrupsiyaning har qanday ko'rinishiga yo'l qo'ymaydi. Barcha xizmatlar belgilangan tartib va O'zbekiston Respublikasi qonunchiligi doirasida ko'rsatiladi.",
    'ac.principles_title'  => 'Asosiy tamoyillar',
    'ac.p1'                => "Tibbiy yordam ko'rsatish tartibi va shartlarining shaffofligi.",
    'ac.p2'                => "Xodimlardan va ularga mukofot talab qilish va berishning mumkin emasligi.",
    'ac.p3'                => "Xizmatlar ko'rsatishda obyektivlik va xolislik.",
    'ac.p4'                => "Korrupsiya faktlari haqidagi xabarlar xavfsizligi va maxfiyligi.",
    'ac.laws_title'        => 'Normativ hujjatlar',
    'ac.l1'                => "O'zbekiston Respublikasining «Korrupsiyaga qarshi kurashish to'g'risida»gi Qonuni (O'RQ-419, 10.01.2017).",
    'ac.l2'                => "O'zbekiston Respublikasi Prezidentining 2019-yil 21-iyundagi PQ-5729-son qarori «O'zbekiston Respublikasida korrupsiyaga qarshi kurashish tizimini yanada takomillashtirish choralari to'g'risida».",
    'ac.l3'                => "Shaxsiy ma'lumotlar va davlat xizmati to'g'risidagi O'zbekiston Respublikasi qonunchiligi.",
    'ac.hotline_title'     => 'Ishonch telefoni',
    'ac.hotline_text'      => "Poraxo'rlik, noqonuniy to'lovlar yoki korrupsiyaning boshqa ko'rinishlari haqidagi faktlar bo'yicha ishonch telefoni va ma'muriyatning elektron pochtasiga anonim murojaat qilish mumkin. Har bir murojaat belgilangan muddatlarda ko'rib chiqiladi.",

    /* 404 sahifa */
    'p404.title' => 'Sahifa topilmadi',
    'p404.text'  => "So'ralgan sahifa mavjud emas yoki ko'chirilgan.",
    'p404.home'  => 'Bosh sahifaga',

    /* Onlayn yozilish */
    'bk.title'        => "Qabulga onlayn yozilish",
    'bk.lead'         => "Besh qadam: yo'nalish, shifokor, sana, bemor ma'lumotlari va tasdiqlash. Bu taxminan ikki daqiqa oladi.",
    'bk.s1'           => "Yo'nalish",
    'bk.s2'           => 'Shifokor',
    'bk.s3'           => 'Sana va vaqt',
    'bk.s4'           => "Ma'lumotlaringiz",
    'bk.s5'           => 'Tasdiqlash',
    'bk.step'         => "{n}-qadam, jami 5",
    'bk.search_ph'    => "Yo'nalishni izlash…",
    'bk.no_doctors'   => "Bu bo'limda hozircha yozilish mumkin bo'lgan shifokor yo'q.",
    'bk.doctors_found'=> '{n}',
    'bk.choose_date'  => "Qabul sanasi va vaqtini tanlang",
    'bk.slots_title'  => "Bo'sh vaqt",
    'bk.no_slots'     => "Tanlangan sanada bo'sh vaqt yo'q. Boshqa kunni tanlang.",
    'bk.select_slot'  => 'Qulay vaqtni tanlang',
    'bk.name'         => "Bemorning F.I.Sh.",
    'bk.name_ph'      => 'Karimov Alisher Botirovich',
    'bk.phone'        => 'Telefon raqami',
    'bk.birth'        => "Tug'ilgan sana",
    'bk.passport'     => 'Pasport (seriya va raqam)',
    'bk.passport_ph'  => 'AA1234567',
    'bk.pinfl'        => 'JShShIR (PINFL)',
    'bk.pinfl_ph'     => '14 raqam',
    'bk.comment'      => "Izoh / shikoyat",
    'bk.comment_ph'   => "Shikoyatlaringiz yoki tashrif maqsadini qisqacha yozing",
    'bk.consent'      => "Qabulga yozilish maqsadida shaxsiy ma'lumotlarimni qayta ishlashga roziman.",
    'bk.submit'       => "Qabulga yozilish",
    'bk.submitting'   => "Yuborilmoqda…",
    'bk.back'         => 'Orqaga',
    'bk.next'         => 'Keyingi',
    'bk.errors'       => "Shaklni to'g'ri to'ldirganingizni tekshiring",
    'bk.err_name'     => "F.I.Sh. ni kiriting (kamida 3 belgi, faqat harflar).",
    'bk.err_phone'    => "+998 (XX) XXX-XX-XX formatida to'g'ri raqam kiriting.",
    'bk.err_birth'    => "Tug'ilgan sanani tekshiring.",
    'bk.err_passport' => 'Pasport formati: ikki harf va 7 raqam (AA1234567).',
    'bk.err_pinfl'    => 'JShShIR 14 raqamdan iborat bo\'lishi kerak.',
    'bk.err_comment'  => "Izoh 1000 belgidan oshmasligi kerak.",
    'bk.err_consent'  => "Shaxsiy ma'lumotlarni qayta ishlashga rozilik talab qilinadi.",
    'bk.err_generic'  => "Yozilishni yaratib bo'lmadi. Tanlangan ma'lumotlarni tekshiring.",
    'bk.err_rate'     => "Manzilingizdan juda ko'p ariza yuborildi. Bir necha daqiqadan so'ng qayta urinib ko'ring.",
    'bk.err_slot'     => "Bu vaqtni endigina band qilishdi. Boshqasini tanlang.",
    'bk.err_day'      => "Bu kunda qabul olib borilmaydi. Boshqa sanani tanlang.",
    'bk.err_csrf'     => "Sessiya tugadi. Sahifani yangilab, qayta urinib ko'ring.",
    'bk.err_honeypot' => "Ariza himoya tizimi tomonidan rad etildi.",
    'bk.done_title'   => "Siz qabulga yozildingiz",
    'bk.done_lead'    => "Ariza raqamini saqlab qo'ying — tashrif paytida ro'yxatga olish bo'limiga ayting.",
    'bk.ticket'       => 'Ariza raqami',
    'bk.instr_title'  => "Tashrif bo'yicha ko'rsatmalar",
    'bk.i1'           => "Qabul vaqtidan 15–20 daqiqa oldin shifoxonaga kelib turing.",
    'bk.i2'           => "Pasport yoki ID-kartani olib keling.",
    'bk.i3'           => "Bo'lsa — yo'llanma, polis va oldingi tekshiruv natijalari.",
    'bk.i4'           => "Kelganingizni tasdiqlash uchun ro'yxatga olish bo'limiga (1-qavat, xol) murojaat qiling.",
    'bk.i5'           => "Kela olmasangiz — quyida ko'rsatilgan telefon orqali ro'yxatga olish bo'limiga xabar bering.",
    'bk.again'        => "Yana bir bemorni yozish",
    'bk.home'         => 'Bosh sahifaga',
    'bk.print'        => "Arizani chop etish",
    'bk.summary'      => "Sizning yozilishingiz",
    'bk.f_doctor'     => 'Shifokor',
    'bk.f_dept'       => "Bo'lim",
    'bk.f_date'       => 'Sana',
    'bk.f_time'       => 'Vaqt',
    'bk.f_office'     => 'Xona',
    'bk.f_patient'    => 'Bemor',
    'bk.f_phone'      => 'Telefon',
    'bk.change'       => "O'zgartirish",
    'bk.today'        => 'Bugun',
    'bk.required_note'=> "* — majburiy maydonlar",

    /* Oylar */
    'month.1'  => 'yanvar',
    'month.2'  => 'fevral',
    'month.3'  => 'mart',
    'month.4'  => 'aprel',
    'month.5'  => 'may',
    'month.6'  => 'iyun',
    'month.7'  => 'iyul',
    'month.8'  => 'avgust',
    'month.9'  => 'sentabr',
    'month.10' => 'oktabr',
    'month.11' => 'noyabr',
    'month.12' => 'dekabr',
];
